joy_node:
  ros__parameters:
    autorepeat_rate: 3.0

joy_controller:
  ros__parameters:
    linear_vel: 0.8         # [m/s]
    angular_vel: 1.0      # [rad/s]
    button_mode_toggle: 6     # Button to toggle teaching/replay mode
    axis_linear: 1
    axis_angular: 3

logger:
  ros__parameters:
    bag_directory: "~/.ros/pfoe_bags"

replay:
  ros__parameters:
    num_particles: 1000
    loop_rate: 10.0
    bag_file: ""              # Optional: specify bag file path (empty = use latest from logger)
